[website] Increase infra to minimum of 4 pods
expo/snack pull request #110
Opened 2021-02-26 18:53 UTC by byCedric

# Why

Discussed this in the response of [issue #1449](https://expo.pagerduty.com/incidents/PJJNR3W).

# How

- Updated `replicas` to `4`
- Added minimum replicas (as per @quinlanj's suggestion)

# Test Plan

- Validate in GCP Kubernetes

2021-02-26 20:21 UTC, nicknovitski requested changes
[Deployment resources](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/deployment-v1/) don't have a `minReplicas` attribute.

[HPA resources](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/horizontal-pod-autoscaler-v1/) do, and you could add one of those to the kustomization instead, while removing this file (no need to set the replicas number at all when an autoscaler will control it).

2021-02-27 01:17 UTC, byCedric commented
Thanks for the context @nicknovitski (cc @quinlanj )

2021-03-25 10:18 UTC, IjzerenHein reviewed
Looks good to me, but I don't have enough knowledge about the topic in order to really tell :)

2021-03-25 17:53 UTC, nicknovitski approved these changes

2021-03-31 07:31 UTC, merged