chore website: fix style for ipad devices horizontally
expo/snack pull request #197
Opened 2021-08-12 19:25 UTC by luism3861

# Why

this PR update `min-width` according issue for react native docs

# How

# Test Plan

i test the resolution for `iPad Air 4th generation`  horizontally real device width for this device is `674px`,   
after run website example i change `min-width: 600` horizontally and vertically

Before: 
![Screen Shot 2021-08-12 at 14 00 15](https://user-images.githubusercontent.com/36824170/129256059-eea6ce97-bad4-4ee0-bef2-7ea45a32a2fc.png)

After:
![Screen Shot 2021-08-12 at 14 00 15](https://user-images.githubusercontent.com/36824170/129256074-3228f32d-75e7-4588-a1ae-c4431e9faf63.png)

2021-08-16 08:38 UTC, IjzerenHein reviewed
In what way is the new appearance better? The text editor is about 50px wide and not usable in this state.
Did you mean to provide screenshots of **embedded** mode? You can preview that using the `/embedded` suffix in the url.

2021-08-18 20:24 UTC, luism3861 commented
> In what way is the new appearance better? The text editor is about 50px wide and not usable in this state.
> Did you mean to provide screenshots of **embedded** mode? You can preview that using the `/embedded` suffix in the url.

Hi @IjzerenHein  thanks for the reply,  after test with `embedded` suffix in url it's correct with the same `px` 

Original:
![Screen Shot 2021-08-18 at 15 11 52](https://user-images.githubusercontent.com/36824170/129967091-2eac6f8d-329e-4a92-8493-17cedefeb8ab.png)

Preview:
![Screen Shot 2021-08-18 at 15 12 04](https://user-images.githubusercontent.com/36824170/129967100-d02a4d7f-f142-48cd-b751-221221e3b1cb.png)

2021-08-19 12:20 UTC, IjzerenHein requested changes
For `embedded` the new minWidth seems fine. However for non embedded, it is too narrow and you can only see a very narrow part of the editor. Please add a separate setting for embedded and use that for embedded only.

```
preview: {
  minWidth: 700,
  embeddedMinWidth: 600,
}
```

2021-08-20 14:49 UTC, luism3861 commented
> For `embedded` the new minWidth seems fine. However for non embedded, it is too narrow and you can only see a very narrow part of the editor. Please add a separate setting for embedded and use that for embedded only.
> 
> ```
> preview: {
>   minWidth: 700,
>   embeddedMinWidth: 600,
> }
> ```

hi @IjzerenHein  thanks for the suggestions my last commit has this changes!. thank you.

2021-08-23 09:01 UTC, IjzerenHein requested changes
Apart from the `matchMedia` issue, this looks good. Could you upload new screenshots for both embedded and non-embedded where the preview pane is both visible and hidden?

2021-08-24 03:42 UTC, luism3861 commented
> Apart from the `matchMedia` issue, this looks good. Could you upload new screenshots for both embedded and non-embedded where the preview pane is both visible and hidden?

No Embedded:
![Screen Shot 2021-08-23 at 22 37 14](https://user-images.githubusercontent.com/36824170/130552234-e2564170-0d64-4a15-b87c-c66ea8107814.png)

Embedded:
![Screen Shot 2021-08-23 at 22 38 17](https://user-images.githubusercontent.com/36824170/130552239-8a04627a-2b0e-483b-bd48-0214f380a0ae.png)

2021-08-24 03:43 UTC, luism3861 commented on website/src/client/components/DevicePreview/DevicePreview.tsx
> +    this.mql = window.matchMedia(VISIBILITY_MEDIA_QUERY_EMBEDDED);
thanks for the suggestion, my last commit has this new changes thank you :)

2021-08-24 08:02 UTC, IjzerenHein approved these changes

2021-08-24 08:12 UTC, merged